name: Python package

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        py: [3.8]
        mypy: ["0.720", "0.812"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.py }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py }}
    - name: Install dependencies
      run: |
        pip install mypy==${{ matrix.mypy }}
    - name: Type check mypy
      run: mypy -p mypy
